name: ci-cd-pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -cover ./... -v

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    environment: ${{github.ref}} #branch name as enviroment
    steps:
      - name: Deploy to environment
        run: |
          if [["${{github.ref}}" == 'refs/head/develop']]; then
            echo "Deploying to develop enviroment..."
          elif ["[${{github.ref}}" == 'refs/heads/staging']]; then
            echo "Deploying to staging enviroment..."
          fi
