name: Terraform Infrastructure Deployment

on:
  workflow_dispatch: #this allows manually pipeline triggering
  push:
    branches: [develop]
    paths: ["terraform/**"] #the action will only run if there is a change to a file listed in terraform folder
  pull_request:
    branches: [develop]
    paths: ["terraform/**"]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform/

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform/

      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
